flags: {}
packages:
- '.'
- location:
    git: https://github.inside.nicta.com.au/AREMI/aremi-web-utils.git
    commit: 0.9.1.1
extra-deps:
- time-units-1.0.0
- lens-datetime-0.2.1
- wai-util-0.8
- http-accept-0.2
- hslogger-template-2.0.3
- servant-blaze-0.4.4.5
- ekg-0.4.0.8
- ekg-json-0.1.0.0
- wai-middleware-metrics-0.2.2
resolver: lts-3.14
local-bin-path: dist
